/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersLogisticsRouteImport } from './routes/orders.logistics'
import { Route as OrdersBillingRouteImport } from './routes/orders.billing'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersLogisticsRoute = OrdersLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersBillingRoute = OrdersBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/orders/billing': typeof OrdersBillingRoute
  '/orders/logistics': typeof OrdersLogisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/orders/billing': typeof OrdersBillingRoute
  '/orders/logistics': typeof OrdersLogisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/orders/billing': typeof OrdersBillingRoute
  '/orders/logistics': typeof OrdersLogisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emails'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/orders/billing'
    | '/orders/logistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emails'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/orders/billing'
    | '/orders/logistics'
  id:
    | '__root__'
    | '/'
    | '/emails'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/orders/billing'
    | '/orders/logistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailsRoute: typeof EmailsRoute
  LeadsRoute: typeof LeadsRoute
  MarketingRoute: typeof MarketingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/logistics': {
      id: '/orders/logistics'
      path: '/logistics'
      fullPath: '/orders/logistics'
      preLoaderRoute: typeof OrdersLogisticsRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/billing': {
      id: '/orders/billing'
      path: '/billing'
      fullPath: '/orders/billing'
      preLoaderRoute: typeof OrdersBillingRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersBillingRoute: typeof OrdersBillingRoute
  OrdersLogisticsRoute: typeof OrdersLogisticsRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersBillingRoute: OrdersBillingRoute,
  OrdersLogisticsRoute: OrdersLogisticsRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailsRoute: EmailsRoute,
  LeadsRoute: LeadsRoute,
  MarketingRoute: MarketingRoute,
  OrdersRoute: OrdersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
